### PR TITLE
Fix for issue17

### PR DESCRIPTION
**Pull request by andalman**
The main change (e962c27518d7c9d08d9b8c1e27d15129a8acac55) in this pull request introduces simple support for including a styles.xml file in a docx. It also introduces two new NSAttributedString keys that allow text to refer to the paragraph or character styles in that styles.xml file.

The other two, much smaller changes, address issues I encountered when using/testing this first change. They aren't required for this feature, and I can split them out into separate issues if that's preferred.

### CODE REVIEW

**Comment by shinjukunian** [comment]
Hi,

sorry for not getting to this any earlier and thank you very much for tackling this issue. 

- I'd prefer if the PR were split into the fixes for sub-/superscript, indentation, and styles.
- I feel that the `DocXConfiguration` should have a more descriptive name that indicates that we are dealing with paragraph styling (maybe `StyleConfiguration`?)
- I feel that `DocXConfiguration` should be an optional property of `DocXOptions`. In the PR, the different between Options and Configuration is not really obvious. I realize that this means shoving all additional functionality into `DocXOptions`, but at least then we have a single object that encapsulates all user-specified, non-default values that dont have a place in `NSAttributedString`, like meta-data, styles, or, in the possibly, page size etc. 

Cheers from Tokyo and again many thanks for your support of this project.


Morten

**Comment by andalman** [comment]
Hi Morten,

Thanks for your feedback!

I’ll file issues for the baseline and indentation fixes and submit separate
PRs for them.

My intention behind DocXConfiguration was that it could be used to hold any
settings that control how docx is *generated*. Currently, its only
properties deal with style, but they don’t strictly have to. For instance,
you mention page size, which I could see fitting in here.

That said, I initially just added these properties to DocXOptions. But then
I re-read this comment at the top of DocXOptions:
/// Options to specify metadata to be saved with the document

And it’s true: all of the properties in DocXOptions deal solely with the
docx’s metadata (and not generation). Since I didn’t want to change the
idea behind this class, I just created another one.

However, I do like the idea of having a single object that contains all non-
NSAttributedString info. So, I’d be happy to move the two properties in
DocXConfiguration to DocXOptions. I’d then propose moving the current,
metadata-related properties in DocXOptions to a DocXMetadata class (and
DocXOptions could have a metadata property). The only reason I didn’t do
this was that this would change the public-facing API.

If we didn’t want to change the public-facing API we could consider
treating DocXConfiguration as the single object that contains all of this
extra information. DocXOptions could be a (deprecated) alias for
DocXMetadata, and we could deprecate the few public functions that take
DocXOptions directly.

Or, maybe it’s just fine to just have all of these ancillary properties in
DocXOptions?

Thoughts?

Thanks again for considering this!

**Comment by shinjukunian** [comment]
Hi,

thank you for your reply. 
I admit that my description of `DocXOptions` only mentions metadata - I guess I was lacking foresight when I wrote this. The naming is, luckily, sufficiently general to accommodate metadata as well as additional output settings. I feel that an optional property like `var documentStyles:DocumenStyleConfiguration?` would work well for the purpose of this PR. This would also get around the optional `URL` parameter in the present `DocXConfiguration `. 
Other output settings (page size etc.) would live in `DocXOptions` as well. Of course the description and would have to be amended to reflect this. To me, this is a pattern that feels somewhat at home in the Cocoa or UIKit world.
In addition, it might be a good idea to have a constructor for `DocumenStyleConfiguration` (or whatever it is called in the end) that takes a `String`. This would make it possible to construct styles dynamically or simply use a string literal in code instead of a resource file. The `URL` constructor would then simply read the content of the specified file.

Again, thank you for your work on this.

**Comment by andalman** [comment]
I understand. I still have a minor preference toward grouping metadata
properties together – since it seems like they are quite different,
conceptually, from other options. But that could always happen in a
separate commit in the future, if necessary.

And I’ll go ahead and add a StyleConfiguration() constructor that takes a
string too.

I’ll get on this this week and submit some updated PRs!

**Comment by shinjukunian** [comment]
Again thank you for your work on this. I agree that we might want  try to separate metadata and document configuration, especially if we continue to add things to `DocXOptions`. Eventually the metadata could be refactored into its own struct and the properties on `DocXOptions` could be deprecated and eventually removed.

I have added a few tests (mostly to figure out what is going on myself) and two additional properties on `DocXStyleConfiguration` for easy access to paragraph and character styles and updated the Readme.

**Comment by andalman** [comment]
﻿Thanks so much for accepting this!In retrospect, I probably should have added a few more tests, too. 😬 I was testing in our app as well, and realized after seeing your changes that the single test I added to DocX was pretty barebones. So thanks for adding more!And the additional properties on DocXStyleConfiguration are a great idea, too!On Jan 12, 2023, at 22:01, Morten ***@***.***> wrote:﻿
Closed #29.

**Pull request closed without merging**
